// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: fleet/v1/fleet.proto

// FleetService is the agent <-> control-plane API. It runs over mTLS: both ends
// present certificates signed by the fleet CA, so an agent's identity is its
// client certificate.

package fleetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Kind int32

const (
	Command_KIND_UNSPECIFIED  Command_Kind = 0
	Command_UPDATE_RULES      Command_Kind = 1
	Command_SET_RESPONSE_MODE Command_Kind = 2
	Command_KILL_PROCESS      Command_Kind = 3
	Command_QUARANTINE        Command_Kind = 4
)

// Enum value maps for Command_Kind.
var (
	Command_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "UPDATE_RULES",
		2: "SET_RESPONSE_MODE",
		3: "KILL_PROCESS",
		4: "QUARANTINE",
	}
	Command_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"UPDATE_RULES":      1,
		"SET_RESPONSE_MODE": 2,
		"KILL_PROCESS":      3,
		"QUARANTINE":        4,
	}
)

func (x Command_Kind) Enum() *Command_Kind {
	p := new(Command_Kind)
	*p = x
	return p
}

func (x Command_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1_fleet_proto_enumTypes[0].Descriptor()
}

func (Command_Kind) Type() protoreflect.EnumType {
	return &file_fleet_v1_fleet_proto_enumTypes[0]
}

func (x Command_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Kind.Descriptor instead.
func (Command_Kind) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{3, 0}
}

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Kernel          string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	EnrollmentToken string                 `protobuf:"bytes,4,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RulesVersion  string                 `protobuf:"bytes,2,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventsProcessed uint64                 `protobuf:"varint,2,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	Alerts          uint64                 `protobuf:"varint,3,opt,name=alerts,proto3" json:"alerts,omitempty"`
	Incidents       uint64                 `protobuf:"varint,4,opt,name=incidents,proto3" json:"incidents,omitempty"`
	RulesVersion    string                 `protobuf:"bytes,5,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetEventsProcessed() uint64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *HeartbeatRequest) GetAlerts() uint64 {
	if x != nil {
		return x.Alerts
	}
	return 0
}

func (x *HeartbeatRequest) GetIncidents() uint64 {
	if x != nil {
		return x.Incidents
	}
	return 0
}

func (x *HeartbeatRequest) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Command_Kind           `protobuf:"varint,1,opt,name=kind,proto3,enum=fleet.v1.Command_Kind" json:"kind,omitempty"`
	Argument      string                 `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"` // mode name, pid, ... interpreted per kind
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetKind() Command_Kind {
	if x != nil {
		return x.Kind
	}
	return Command_KIND_UNSPECIFIED
}

func (x *Command) GetArgument() string {
	if x != nil {
		return x.Argument
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AlertReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RuleId            string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName          string                 `protobuf:"bytes,5,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Severity          string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	TechniqueId       string                 `protobuf:"bytes,7,opt,name=technique_id,json=techniqueId,proto3" json:"technique_id,omitempty"`
	TechniqueName     string                 `protobuf:"bytes,8,opt,name=technique_name,json=techniqueName,proto3" json:"technique_name,omitempty"`
	Pid               uint32                 `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName       string                 `protobuf:"bytes,10,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessExecutable string                 `protobuf:"bytes,11,opt,name=process_executable,json=processExecutable,proto3" json:"process_executable,omitempty"`
	DestinationIp     string                 `protobuf:"bytes,12,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	RiskScore         int32                  `protobuf:"varint,13,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	IsIncident        bool                   `protobuf:"varint,14,opt,name=is_incident,json=isIncident,proto3" json:"is_incident,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlertReport) Reset() {
	*x = AlertReport{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertReport) ProtoMessage() {}

func (x *AlertReport) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertReport.ProtoReflect.Descriptor instead.
func (*AlertReport) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *AlertReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AlertReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AlertReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AlertReport) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AlertReport) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *AlertReport) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertReport) GetTechniqueId() string {
	if x != nil {
		return x.TechniqueId
	}
	return ""
}

func (x *AlertReport) GetTechniqueName() string {
	if x != nil {
		return x.TechniqueName
	}
	return ""
}

func (x *AlertReport) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AlertReport) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *AlertReport) GetProcessExecutable() string {
	if x != nil {
		return x.ProcessExecutable
	}
	return ""
}

func (x *AlertReport) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *AlertReport) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AlertReport) GetIsIncident() bool {
	if x != nil {
		return x.IsIncident
	}
	return false
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      uint64                 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *ReportAck) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

type RulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	KnownVersion  string                 `protobuf:"bytes,2,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesRequest) Reset() {
	*x = RulesRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesRequest) ProtoMessage() {}

func (x *RulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesRequest.ProtoReflect.Descriptor instead.
func (*RulesRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *RulesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RulesRequest) GetKnownVersion() string {
	if x != nil {
		return x.KnownVersion
	}
	return ""
}

type RulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Unchanged     bool                   `protobuf:"varint,2,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	Files         []*RuleFile            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesResponse) Reset() {
	*x = RulesResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse) ProtoMessage() {}

func (x *RulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse.ProtoReflect.Descriptor instead.
func (*RulesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *RulesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RulesResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

func (x *RulesResponse) GetFiles() []*RuleFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type RuleFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleFile) Reset() {
	*x = RuleFile{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleFile) ProtoMessage() {}

func (x *RuleFile) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleFile.ProtoReflect.Descriptor instead.
func (*RuleFile) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *RuleFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_fleet_v1_fleet_proto protoreflect.FileDescriptor

const file_fleet_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x14fleet/v1/fleet.proto\x12\bfleet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\rEnrollRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12)\n" +
	"\x10enrollment_token\x18\x04 \x01(\tR\x0fenrollmentToken\"P\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rrules_version\x18\x02 \x01(\tR\frulesVersion\"\xb3\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10events_processed\x18\x02 \x01(\x04R\x0feventsProcessed\x12\x16\n" +
	"\x06alerts\x18\x03 \x01(\x04R\x06alerts\x12\x1c\n" +
	"\tincidents\x18\x04 \x01(\x04R\tincidents\x12#\n" +
	"\rrules_version\x18\x05 \x01(\tR\frulesVersion\"\xba\x01\n" +
	"\aCommand\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.fleet.v1.Command.KindR\x04kind\x12\x1a\n" +
	"\bargument\x18\x02 \x01(\tR\bargument\"g\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUPDATE_RULES\x10\x01\x12\x15\n" +
	"\x11SET_RESPONSE_MODE\x10\x02\x12\x10\n" +
	"\fKILL_PROCESS\x10\x03\x12\x0e\n" +
	"\n" +
	"QUARANTINE\x10\x04\"B\n" +
	"\x11HeartbeatResponse\x12-\n" +
	"\bcommands\x18\x01 \x03(\v2\x11.fleet.v1.CommandR\bcommands\"\xe5\x03\n" +
	"\vAlertReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x05 \x01(\tR\bruleName\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12!\n" +
	"\ftechnique_id\x18\a \x01(\tR\vtechniqueId\x12%\n" +
	"\x0etechnique_name\x18\b \x01(\tR\rtechniqueName\x12\x10\n" +
	"\x03pid\x18\t \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\n" +
	" \x01(\tR\vprocessName\x12-\n" +
	"\x12process_executable\x18\v \x01(\tR\x11processExecutable\x12%\n" +
	"\x0edestination_ip\x18\f \x01(\tR\rdestinationIp\x12\x1d\n" +
	"\n" +
	"risk_score\x18\r \x01(\x05R\triskScore\x12\x1f\n" +
	"\vis_incident\x18\x0e \x01(\bR\n" +
	"isIncident\"'\n" +
	"\tReportAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived\"N\n" +
	"\fRulesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rknown_version\x18\x02 \x01(\tR\fknownVersion\"q\n" +
	"\rRulesResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tunchanged\x18\x02 \x01(\bR\tunchanged\x12(\n" +
	"\x05files\x18\x03 \x03(\v2\x12.fleet.v1.RuleFileR\x05files\"8\n" +
	"\bRuleFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2\x8c\x02\n" +
	"\fFleetService\x12;\n" +
	"\x06Enroll\x12\x17.fleet.v1.EnrollRequest\x1a\x18.fleet.v1.EnrollResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.fleet.v1.HeartbeatRequest\x1a\x1b.fleet.v1.HeartbeatResponse\x12<\n" +
	"\fReportAlerts\x12\x15.fleet.v1.AlertReport\x1a\x13.fleet.v1.ReportAck(\x01\x12;\n" +
	"\bGetRules\x12\x16.fleet.v1.RulesRequest\x1a\x17.fleet.v1.RulesResponseB;Z9github.com/argus-edr/argus/internal/fleet/fleetpb;fleetpbb\x06proto3"

var (
	file_fleet_v1_fleet_proto_rawDescOnce sync.Once
	file_fleet_v1_fleet_proto_rawDescData []byte
)

func file_fleet_v1_fleet_proto_rawDescGZIP() []byte {
	file_fleet_v1_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)))
	})
	return file_fleet_v1_fleet_proto_rawDescData
}

var file_fleet_v1_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fleet_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fleet_v1_fleet_proto_goTypes = []any{
	(Command_Kind)(0),             // 0: fleet.v1.Command.Kind
	(*EnrollRequest)(nil),         // 1: fleet.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 2: fleet.v1.EnrollResponse
	(*HeartbeatRequest)(nil),      // 3: fleet.v1.HeartbeatRequest
	(*Command)(nil),               // 4: fleet.v1.Command
	(*HeartbeatResponse)(nil),     // 5: fleet.v1.HeartbeatResponse
	(*AlertReport)(nil),           // 6: fleet.v1.AlertReport
	(*ReportAck)(nil),             // 7: fleet.v1.ReportAck
	(*RulesRequest)(nil),          // 8: fleet.v1.RulesRequest
	(*RulesResponse)(nil),         // 9: fleet.v1.RulesResponse
	(*RuleFile)(nil),              // 10: fleet.v1.RuleFile
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_fleet_v1_fleet_proto_depIdxs = []int32{
	0,  // 0: fleet.v1.Command.kind:type_name -> fleet.v1.Command.Kind
	4,  // 1: fleet.v1.HeartbeatResponse.commands:type_name -> fleet.v1.Command
	11, // 2: fleet.v1.AlertReport.timestamp:type_name -> google.protobuf.Timestamp
	10, // 3: fleet.v1.RulesResponse.files:type_name -> fleet.v1.RuleFile
	1,  // 4: fleet.v1.FleetService.Enroll:input_type -> fleet.v1.EnrollRequest
	3,  // 5: fleet.v1.FleetService.Heartbeat:input_type -> fleet.v1.HeartbeatRequest
	6,  // 6: fleet.v1.FleetService.ReportAlerts:input_type -> fleet.v1.AlertReport
	8,  // 7: fleet.v1.FleetService.GetRules:input_type -> fleet.v1.RulesRequest
	2,  // 8: fleet.v1.FleetService.Enroll:output_type -> fleet.v1.EnrollResponse
	5,  // 9: fleet.v1.FleetService.Heartbeat:output_type -> fleet.v1.HeartbeatResponse
	7,  // 10: fleet.v1.FleetService.ReportAlerts:output_type -> fleet.v1.ReportAck
	9,  // 11: fleet.v1.FleetService.GetRules:output_type -> fleet.v1.RulesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_fleet_v1_fleet_proto_init() }
func file_fleet_v1_fleet_proto_init() {
	if File_fleet_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_v1_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_v1_fleet_proto_depIdxs,
		EnumInfos:         file_fleet_v1_fleet_proto_enumTypes,
		MessageInfos:      file_fleet_v1_fleet_proto_msgTypes,
	}.Build()
	File_fleet_v1_fleet_proto = out.File
	file_fleet_v1_fleet_proto_goTypes = nil
	file_fleet_v1_fleet_proto_depIdxs = nil
}
