package main

import (
	"net/http"
	"sort"
	"strconv"
	"strings"
)

// MITRE ATT&CK Navigator layer (schema 4.5): a JSON document the public
// Navigator tool imports to render a coverage matrix. ARGUS produces one from the
// served ruleset so a team can see, and share, exactly what it detects.
type navigatorLayer struct {
	Name        string           `json:"name"`
	Versions    navigatorVersion `json:"versions"`
	Domain      string           `json:"domain"`
	Description string           `json:"description"`
	Techniques  []navigatorTech  `json:"techniques"`
	Gradient    navigatorGrad    `json:"gradient"`
}

type navigatorVersion struct {
	Attack    string `json:"attack"`
	Navigator string `json:"navigator"`
	Layer     string `json:"layer"`
}

type navigatorTech struct {
	TechniqueID string `json:"techniqueID"`
	Score       int    `json:"score"`
	Comment     string `json:"comment,omitempty"`
	Enabled     bool   `json:"enabled"`
}

type navigatorGrad struct {
	Colors   []string `json:"colors"`
	MinValue int      `json:"minValue"`
	MaxValue int      `json:"maxValue"`
}

// handleNavigator builds an ATT&CK Navigator layer from the served rules,
// scoring each technique by how many rules cover it. The console offers it for
// download; it also imports straight into the public Navigator.
func (a *adminAPI) handleNavigator(w http.ResponseWriter, _ *http.Request) {
	catalogue, err := a.rules.Catalogue()
	if err != nil {
		writeError(w, http.StatusInternalServerError, "rule catalogue: "+err.Error())
		return
	}
	rulesByTechnique := map[string][]string{}
	for _, rule := range catalogue {
		id := rule.Technique.ID
		if id == "" {
			continue
		}
		rulesByTechnique[id] = append(rulesByTechnique[id], rule.ID)
	}

	techniques := make([]navigatorTech, 0, len(rulesByTechnique))
	maxScore := 1
	for id, ruleIDs := range rulesByTechnique {
		sort.Strings(ruleIDs)
		techniques = append(techniques, navigatorTech{
			TechniqueID: id,
			Score:       len(ruleIDs),
			Comment:     strconv.Itoa(len(ruleIDs)) + " rule(s): " + strings.Join(ruleIDs, ", "),
			Enabled:     true,
		})
		if len(ruleIDs) > maxScore {
			maxScore = len(ruleIDs)
		}
	}
	sort.Slice(techniques, func(i, j int) bool { return techniques[i].TechniqueID < techniques[j].TechniqueID })

	layer := navigatorLayer{
		Name:        "ARGUS detection coverage",
		Versions:    navigatorVersion{Attack: "14", Navigator: "4.9.1", Layer: "4.5"},
		Domain:      "enterprise-attack",
		Description: "Generated by ARGUS from ruleset " + a.rules.Version(),
		Techniques:  techniques,
		Gradient:    navigatorGrad{Colors: []string{"#1a2130", "#134e4a", "#2dd4bf"}, MinValue: 0, MaxValue: maxScore},
	}
	w.Header().Set("Content-Disposition", `attachment; filename="argus-attack-navigator.json"`)
	writeJSON(w, http.StatusOK, layer)
}
